# Send a notification email in case of a CI failure
name: Email notification

on:
  workflow_call:
    inputs:
      conclusion:
        description: "Workflow conclusion"
        required: true
        type: string


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.conclusion != 'success'  # notify only if failure
        uses: dawidd6/action-send-mail@v16
        with:
          server_address: ${{ secrets.STORM_CI_MAIL_SERVER }}
          server_port: 587
          username: ${{ secrets.STORM_CI_MAIL_USERNAME }}
          password: ${{ secrets.STORM_CI_MAIL_PASSWORD }}
          subject: "[You broke it] CI run failed for ${{ github.repository }}"
          body:
            "CI job of ${{ github.repository }} has failed for commit ${{ github.sha }}.\n\
            The error type is: ${{ inputs.conclusion }}.\n\n\
            For more information, see https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          to: ${{ secrets.STORM_CI_MAIL_RECIPIENTS }}
          from: Github Actions <you-broke-it@stormchecker.org>
